### PR TITLE
fixes for the custom keyboard

### PR DESCRIPTION
**Pull request by jayrox**
this pull request is to resolve the issue with the keyboard not displaying. it also resolves an issue where couchpotato only has one profile setup. previously if there was only one profile, the keyboard wouldn't  be created and it wasnt obvious to the user how to proceed. it also adds a note to the bottom of the list to select an item from the custom keyboard.

### CODE REVIEW

**Comment by onedr0p** [comment]
Good work! I just reviewed this PR and will merge it into master shortly.

**Comment by jayrox** [comment]
Thank you! I was looking into updating the Sonarr bot also to use the custom keyboards. Was there a particular reason you went with the menu on one and custom keyboards on the other?

**Comment by onedr0p** [comment]
The custom keyboard on sonarr is yet to be implemented. The one for couchpotato was just recently added. Feel free to add the functionality to the sonarr bot and send a PR. Please use the same logic though, thanks!

**Comment by jayrox** [comment]
Ok, cool. Yeah, I'll have a look and keep the same flow and make it feel like the couchpotato version.

**Comment by onedr0p** [comment]
Thanks! I see your PR. I'll get it merged in tonight.

**Pull request merged**
