### PR TITLE
Bot will respond with custom keyboards

### PR DESCRIPTION
**Pull request by bybeet**
Expand the telegram-couchpotato-bot to take advantage of the Telegram bot [custom keyboards](https://core.telegram.org/bots#keyboards).
* Add custom keyboard to response
* Change regex for movie and profile handling
* Add `replyWithError` function

**What motivated this change?**
My primary use case for the Telegram CouchPotato Bot is adding movies on the go. The existing command structure is very terse, but requires more typing than I want to do for a task like this on a phone.

**What was the solution?**
Use the custom keyboards functionality of the Telegram Bot API. As we build up the response body, also construct an array to be sent as the keyboard options.

**What is the impact of this change?**
Less typing is involved in adding a new movie. The regex expression the the bot looks for has changed to accommodate the custom keyboard. Changing to `1) Movie Name` and `A) Profile` made the keyboard options cleaner and allowed the bulk of the bot logic to remain the same.

If it is desirable for the `/m [n]` and `/p [n]` commands to stay some refactoring could be done to pull movie and profile logic out into their own functions, to be called on both `/m 1` and `1) movie name` regex expressions.

**Show me how this custom keyboard looks**
Desktop Client (OSX)
desktop client select movie
desktop client select profile

Mobile Client (iOS)

### CODE REVIEW

**Comment by onedr0p** [comment]
Nice job! I'll give this a further look soon. One quick thing I noticed was the use of letters in the quality profile. I know we are somewhat limited here in terms of using the keyboard actions. My only concern is if we need to send another question with responses, for example, using couchpotatos custom categories.

**Comment by bybeet** [comment]
One option would be to do away with 1,2,3,A,B,C and use the cache to maintain the state/progress in adding a movie. Start with a catch-all function that then based on the cache value either handles the movie or the profile. This approach would work well for any number of additional questions and keyboard actions would also be cleaner without the prepended `1)`.

**Comment by onedr0p** [comment]
Sounds like a plan if your up to it :) If not I'll be able to work on it in a couple weeks.

**Comment by bybeet** [comment]
Updated code to support the custom keyboard without regex matching on a prepended value. Bot has some error handling around messages that aren't commands or options from the custom keyboard.

```
User, [30.12.15 11:18]
bob

CouchPotatoBot, [30.12.15 11:18]
Oh no! Error: Try searching for a movie first with /q movie name
```

```
User, [30.12.15 11:19]
/q die hard

CouchPotatoBot, [30.12.15 11:19]
Found 3 movies:
1) Die Hard ( http://imdb.com/title/tt0095016 ) - 1988 - 8.2/10 - 131m
2) Die Hard 2 ( https://www.themoviedb.org/movie/tt0099423 ) - 1990 - 124m
3) Live Free or Die Hard ( https://www.themoviedb.org/movie/tt0337978 ) - 2007 - 128m

User, [30.12.15 11:19]
potato

CouchPotatoBot, [30.12.15 11:19]
Oh no! Error: Could not find the movie with title "potato"
```

[Line 164](https://github.com/onedr0p/telegram-couchpotato-bot/pull/11/files#diff-c164f763bc93c936ce282294370097faR164) is where the logic lives to handle a message that isn't a command (doesn't have the leading forward-slash).

**Comment by onedr0p** [comment]
Wow! Good work, I'll get this merged in right away! Thanks a lot.

**Pull request merged**
